### ISSUE TITLE
File Size

### ISSUE THREAD

**Issue by Oregano1963** [G2-Games/Old-Ores-MC#1]
This isn't the biggest issue but why is this pack 41KB when the old ores for java pack is 8KB?

**Comment by G2-Games** [comment]
I don't know what pack you're referencing, but it could be a lot of reasons. Is 41KB somehow too large for you?

**Comment by G2-Games** [comment]
Additionally, this version properly supports the top and sides of the deepslate textures, and makes copper match the old style, which adds quite a few more files, increasing size.

**Comment by G2-Games** [comment]
I decreased the overall pack size to ~15KB by stripping PNG metadata, however the pack is still has more features as compared to the other one you mentioned, and therefore the file size will always be larger.
